### ISSUE TITLE
Add BMS Support

### ISSUE THREAD

**Issue by Eve-ning** [Eve-ning/reamberPy#20]
**Include as many relevant documents/sites as possible to help me decipher the file format**
https://fileformats.fandom.com/wiki/Be-Music_Script

https://hitkey.nekokan.dyndns.info/cmds.htm

**Comment by Eve-ning** [comment]
obj: slash bms dls http://slash24th.web.fc2.com/nanidosp.htm

**Comment by Eve-ning** [comment]
Due to lack of interest in keysounding in competitive VSRG scene in general, keysound conversion will not be supported/negligible.

**Comment by Eve-ning** [comment]
Writing will also not be supported unless there's high demand.

**Comment by kadoen** [comment]
Seems like a couple of things break the BMSMap.readFile method:
 - Non-integer BPM (attempt at bin -> int conversion fails)
 - Reference to a sample that has not been defined in the #WAV header (maybe could be fixed with an option to ignore all samples and just read the notes)

I attach [an example .bme](https://github.com/Eve-ning/reamberPy/files/6603290/nhelv_ruina.zip) that includes both. Starting BPM is defined as `#BPM 175.89`, and sample `ZZ` is called in many measures, starting at `#03214` for example - I think BMS emulators just ignore the sample and treat it as a sound-less note.

**Comment by Eve-ning** [comment]
1. Changed BMS to cast BPM as floats (didn't know they could use floats)
2. Allow conditional gets (sample will be None if sample isn't found)

fixed in branch 0.0.20

Will close this, feel free to open another issue, doing a bit of house keeping on old issues
